name: 企鹅读书日常任务

on:
  workflow_dispatch:
  schedule:
     - cron: '* */1 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQREAD_BODY: ${{ secrets.QQREAD_BODY }}
        QQREAD_TIMEURL: ${{ secrets.QQREAD_TIMEURL }}
        QQREAD_TIMEHD: ${{ secrets.QQREAD_TIMEHD }}
        QQREAD_CASH: ${{ secrets.QQREAD_CASH }} 
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.QQREAD_TIMEHD
        run: |
          npm install
      - name: '运行 【企鹅读书日常任务】'
        if: env.QQREAD_TIMEHD
        run: |
          node qqreadnodeOnlyMession.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
