name: sync-ziye-script
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-ziye-script
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.SECRET_HJ }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-ziye-script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE.git"
          source_branch: "main"
          destination_branch: "sync-ziye-script"
          github_token: ${{ secrets.SECRET_HJ }}
