name: sync-demo2099-jd_jscripts
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-demo2099-jd_jscripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.SECRET_HJ }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync sync-demo2099-jd_jscripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/demo2099/jd_jscripts.git"
          source_branch: "master"
          destination_branch: "sync-demo2099-jd_jscripts"
          github_token: ${{ secrets.SECRET_HJ }}
