name: UnicomTask

on:
  workflow_dispatch:
  schedule:
     - cron: '33 22 * * *'
  watch:
    types: started
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      run: |
        git clone https://github.com/fenglinefg/hello-world.git -b UnicomTask ~/Scripts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Install dependencies
      run: |
        cd ~/Scripts
        pip install -r requirements.txt
    - name: Build and publish
      env:
        USERS_COVER: ${{ secrets.USERS_COVER }}
      run: |
        cd ~/Scripts
        echo "$USERS_COVER" > ./config.json
        python main.py
