name: 联通营业厅签到领积分

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    #格林尼治时间22：11，东八区北京时间6：11
    - cron: 11 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/QiuYueBaiJXW/CN-Unicom-AutoSign.git ~/QiuYueBaiJXW
      - name: Install extensions
        run: |
          cd ~/QiuYueBaiJXW
          pip3 install setuptools
      - name: Run program
        env:
           cookie: ${{ secrets.LT_COOKIE }}
        run: |
          cd ~/QiuYueBaiJXW
          python3 UnicomAutoGetCoin.py ${cookie}
          
